#!/bin/sh -e

MAJOR=1.3
PATCH=2

docker build --pull --tag jsonxr/spigot:${MAJOR}.${PATCH} .
docker tag jsonxr/spigot:${MAJOR}.${PATCH} jsonxr/spigot:${MAJOR}
docker tag jsonxr/spigot:${MAJOR}.${PATCH} jsonxr/spigot:latest
